### ISSUE TITLE
Adding new java file to the bundle?

### ISSUE THREAD

**Issue by daniel112** [gios-asu/sustainability-tower-defense#4]
I'm semi confused about this whole webpack thing. 
I know that all the js files and css files will be put into 1 file called bundle.js before the game is running.

I am trying to add a new js file to the src, but how would I compile it so bundle.js picks it up?

**Comment by daniel112** [comment]
@rraub @nathan-rollins

**Comment by ndrollin** [comment]
There are a couple ways to go at this. First, make sure you understand the contents of webpack.config.js.  (For instance, [take a  look at this intro article](https://medium.com/@dabit3/beginner-s-guide-to-webpack-b1f1a3638460#.9g7t3xbnp)).

So, the line: 

```
   entry: "./src/game.js",
```

is the entry point (starting point) for webpack. It starts there, and looks for all the dependencies that file (or files) need and bundles them all together.

So solution one is to include() your new js file inside the main app file (game.js in this project). Webpack looks inside game.js, sees that it needs your new js file and it goes and grabs it.

Alternately, 'entry' also accepts an array of files, so this is also valid:

```
module.exports = {
  entry: ["./src/game.js", "./src/new.js"],
  output: {
    path: __dirname + "/build",
    filename: "bundle.js"
  },
...
```

Webpack will get each of the files you list in the 'entry' array.

**Comment by rraub** [comment]
Also its Java**script** :smile:
